export const TaskCommandType = {
	CreateTask: 'createTask',
	CreateTaskInPool: 'createTaskInPool',
	ChangeStartDate: 'changeStartDate',
	ChangeEndDate: 'changeEndDate',
	UpdateTitle: 'updateTitle',
	UpdateDescription: 'updateDescription',
	ChangeStatus: 'changeStatus',
	DeleteTask: 'deleteTask',
	PlanFromEnd: 'planFromEnd',
	AssignSchedule: 'assignSchedule',
	MoveTask: 'moveTask',
	ResizeTask: 'resizeTask',
	UpdateFields: 'updateFields',
} as const