package com.khan366kos.atlas.project.backend.transport

import com.khan366kos.atlas.project.backend.transport.commands.ChangeTaskEndDateCommandDto
import com.khan366kos.atlas.project.backend.transport.commands.ChangeTaskStartDateCommandDto
import com.khan366kos.atlas.project.backend.transport.commands.CreateDependencyCommandDto
import com.khan366kos.atlas.project.backend.transport.commands.CreateTaskInPoolCommandDto
import com.khan366kos.atlas.project.backend.transport.enums.DependencyTypeDto
import com.khan366kos.atlas.project.backend.transport.enums.ProjectTaskStatus
import com.khan366kos.atlas.project.backend.transport.ganttProjectPlan.GanttProjectPlanDto
import com.khan366kos.atlas.project.backend.transport.plan.GantPlanDto
import com.khan366kos.atlas.project.backend.transport.calendar.GanttCalendarDto
import com.khan366kos.atlas.project.backend.transport.timelineCalendar.TimelineCalendarDto
import dev.adamko.kxstsgen.KxsTsGenerator
import kotlinx.serialization.KSerializer
import java.io.File

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Usage: generateTypeScript <outputDirectory>")
        return
    }

    val outputDir = File(args[0])
    outputDir.mkdirs()

    val generator = KxsTsGenerator()

    // Список всех DTO для генерации
    val dtoSerializers = listOf<KSerializer<*>>(
        // Основные DTO
        GanttProjectPlanDto.serializer(),
        GanttTaskDto.serializer(),
        GanttDependencyDto.serializer(),
        TaskDto.serializer(),
        ScheduledTaskDto.serializer(),
        ScheduleDeltaDto.serializer(),
        ScheduleUpdateDto.serializer(),
        CreateProjectTaskRequest.serializer(),
        UpdateProjectTaskRequest.serializer(),
        WorkCalendar.serializer(),

        // Calendar DTOs
        GanttCalendarDto.serializer(),
        TimelineCalendarDto.serializer(),

        // Plan DTO
        GantPlanDto.serializer(),

        // Command DTOs
        CreateTaskInPoolCommandDto.serializer(),
        CreateDependencyCommandDto.serializer(),
        ChangeTaskStartDateCommandDto.serializer(),
        ChangeTaskEndDateCommandDto.serializer(),

        // Enums
        ProjectTaskStatus.serializer(),
        DependencyTypeDto.serializer(),
    )

    // Очистка директории перед генерацией
    outputDir.listFiles()?.forEach { it.deleteRecursively() }

    // Генерация файлов
    val generatedFiles = mutableListOf<String>()
    dtoSerializers.forEach { serializer ->
        try {
            val serialName = serializer.descriptor.serialName
            val (relativePath, fileName) = extractPackageAndFileName(serialName)
            
            val tsInterface = generator.generate(serializer)
            
            val subDir = if (relativePath.isNotEmpty()) {
                File(outputDir, relativePath)
            } else {
                outputDir
            }
            subDir.mkdirs()
            
            val outputFile = File(subDir, fileName)
            outputFile.writeText(tsInterface)
            
            val fullPath = if (relativePath.isNotEmpty()) {
                "$relativePath/$fileName"
            } else {
                fileName
            }
            generatedFiles.add(fullPath)
            println("Generated: $fullPath")
        } catch (e: Exception) {
            val serialName = try {
                serializer.descriptor.serialName
            } catch (e2: Exception) {
                "unknown"
            }
            println("Error generating $serialName: ${e.message}")
            e.printStackTrace()
        }
    }

    // Генерация index.ts для удобного импорта
    // Проблема: kxs-ts-gen-core генерирует все зависимые типы (enum, nested interfaces) в каждом файле
    // Решение: экспортируем только главные интерфейсы из каждого файла, избегая дублирования
    val indexContent = buildString {
        appendLine("// Auto-generated by generateTypeScript Gradle task")
        appendLine("// Note: Import types directly from their respective files to avoid conflicts")
        appendLine("//       This file exports only the main DTO from each file")
        appendLine()
        
        // Основные DTO без зависимостей
        appendLine("// Main DTOs")
        appendLine("export type { GanttProjectPlanDto } from './ganttProjectPlan/gantt-project-plan.dto'")
        appendLine("export type { GanttTaskDto } from './gantt-task.dto'")
        appendLine("export type { GanttDependencyDto } from './gantt-dependency.dto'")
        appendLine("export type { TaskDto } from './task.dto'")
        appendLine("export type { ScheduledTaskDto } from './scheduled-task.dto'")
        appendLine("export type { ScheduleDeltaDto, ScheduleUpdateDto } from './schedule-delta.dto'")
        appendLine("export type { CreateProjectTaskRequest } from './create-project-task.dto'")
        appendLine("export type { UpdateProjectTaskRequest } from './update-project-task.dto'")
        appendLine("export type { WorkCalendar } from './work-calendar.dto'")
        appendLine()
        
        // Calendar DTOs
        appendLine("// Calendar")
        appendLine("export type { GanttCalendarDto } from './calendar/gantt-calendar.dto'")
        appendLine("export type { TimelineCalendarDto } from './timelineCalendar/timeline-calendar.dto'")
        appendLine()
        
        // Plan DTO
        appendLine("// Plan")
        appendLine("export type { GantPlanDto } from './plan/gant-plan.dto'")
        appendLine()
        
        // Command DTOs
        appendLine("// Commands")
        appendLine("export type { CreateTaskInPoolCommandDto } from './commands/create-task-in-pool-command.dto'")
        appendLine("export type { CreateDependencyCommandDto } from './commands/create-dependency-command.dto'")
        appendLine("export type { ChangeTaskStartDateCommandDto } from './commands/change-task-start-date-command.dto'")
        appendLine("export type { ChangeTaskEndDateCommandDto } from './commands/change-task-end-date-command.dto'")
        appendLine()
        
        // Enums - экспортируем из отдельных файлов
        appendLine("// Enums")
        appendLine("export { ProjectTaskStatus } from './enums/project-task-status.enum'")
        appendLine("export { DependencyTypeDto } from './enums/dependency-status.enum'")
    }
    val indexFile = File(outputDir, "index.ts")
    indexFile.writeText(indexContent)
    println("Generated: index.ts")

    println("\nTypeScript generation complete! Output: ${outputDir.absolutePath}")
}

/**
 * Извлекает имя пакета и имя файла из serialName.
 * 
 * Примеры:
 * - "com.khan366kos.atlas.project.backend.transport.calendar.GanttCalendarDto"
 *   → ("calendar", "gantt-calendar.dto.ts")
 * - "com.khan366kos.atlas.project.backend.transport.GanttTaskDto"
 *   → ("", "gantt-task.dto.ts")
 * - "com.khan366kos.atlas.project.backend.transport.enums.ProjectTaskStatus"
 *   → ("enums", "project-task-status.enum.ts")
 */
private fun extractPackageAndFileName(serialName: String): Pair<String, String> {
    val parts = serialName.split('.')
    val simpleName = parts.last()
    
    // Берём последнюю часть пакета после "transport"
    // com.khan366kos.atlas.project.backend.transport.XXX → ""
    // com.khan366kos.atlas.project.backend.transport.calendar.XXX → "calendar"
    // com.khan366kos.atlas.project.backend.transport.enums.XXX → "enums"
    val transportIndex = parts.indexOf("atlas-project-backend-transport".replace("-", ""))
        .takeIf { it >= 0 } ?: parts.indexOfLast { it.contains("transport") }
    
    val relativePath = if (transportIndex >= 0 && transportIndex < parts.size - 2) {
        // Есть подпакет после transport
        parts[transportIndex + 1]
    } else {
        // Нет подпакета - файлы в корне
        ""
    }
    
    // Преобразуем CamelCase в kebab-case
    val fileNameBase = simpleName
        .replace(Regex("(?<!^)([A-Z])")) { "-${it.groupValues[1].lowercase()}" }
        .lowercase()
    
    // Определяем расширение и убираем дублирующие суффиксы
    val isEnum = parts.any { it == "enums" } || 
        (simpleName.endsWith("Status") && !simpleName.endsWith("CalendarStatus")) || 
        simpleName.endsWith("TypeDto")
    
    val (baseName, extension) = if (isEnum) {
        // Для enum: ProjectTaskStatus → project-task-status.enum.ts
        // DependencyTypeDto → dependency-type.enum.ts
        val nameWithoutSuffix = fileNameBase
            .removeSuffix("-status")
            .removeSuffix("-type-dto")
            .removeSuffix("-type")
        "$nameWithoutSuffix-status".removePrefix("-") to ".enum.ts"
    } else {
        // Для DTO: убираем только финальный -dto, -request, но оставляем -calendar, -task, -command и т.д.
        val nameWithoutSuffix = fileNameBase
            .removeSuffix("-dto")
            .removeSuffix("-request")
        nameWithoutSuffix to ".dto.ts"
    }
    
    val fileName = "$baseName$extension"
    
    return relativePath to fileName
}
